### ISSUE TITLE
Anlagen neuer Anzeigen -> Preis wird nicht übertragen

### ISSUE THREAD

**Issue by omili** [gastonx/AnzeigenChef-Mac#1]
Neue Anzeigen können nicht erstellt werden, da der Preis anscheinend nicht als Integer (z.B. "470" sondern als "470.00000" übertragen wird.

![bildschirmfoto 2015-05-28 um 20 01 51](https://cloud.githubusercontent.com/assets/12647957/7867128/6c2bd7b2-0574-11e5-89c9-f8fd2ca831ce.png)

Platfform: Mac OS X 10.10.3

**Comment by gastonx** [comment]
Hallo,

vielen Dank für Deinen Hinweis. Das liegt in der Tat an der 1.2, da ich bei dieser leider noch die Währungsformatierung drin hatte.

Ich habe soeben die 1.3 hochgeladen (Unter Releases). Damit klappt das. Da die Datenbank umbenannt wurde, muss man leider die Daten nochmal eintippen. Aber ab jetzt ändert sich das nicht mehr.

Vielen Dank für Deinen Test.

**Comment by omili** [comment]
Hi Michael!
Vielen Dank für den schnellen fix und für allem fürs das coole Tool. Wir probieren das gleich nochmal aus und wenn alles gut klappt, gibts auch "bares in die Kaffeekasse" ;-)
Danke nochmal für deinen tollen Einsatz,
der Oliver


     Michael Geschwill <notifications@github.com> schrieb am 20:14 Donnerstag, 28.Mai 2015:
   

 Hallo,vielen Dank für Deinen Hinweis. Das liegt in der Tat an der 1.2, da ich bei dieser leider noch die Währungsformatierung drin hatte.Ich habe soeben die 1.3 hochgeladen (Unter Releases). Damit klappt das. Da die Datenbank umbenannt wurde, muss man leider die Daten nochmal eintippen. Aber ab jetzt ändert sich das nicht mehr.Vielen Dank für Deinen Test.—

**Comment by gastonx** [comment]
Gerne :)
Nur dran denken, ich bin noch ganz am Anfang, fehlt noch einiges was noch rein muss.
Nächster Schritt sind die Kategorien für die Templates ;)

Danke nochmal für die Zeit.
