### ISSUE TITLE
AnzeigenChef should use the same icons for visitors and favourites

### ISSUE THREAD

**Issue by d-a-n** [gastonx/AnzeigenChef-Mac#5]
Currently AnzeigenChef uses the eye icon for displaying if users have marked the ad as favourite and a people icon for visitors. eBay Kleinanzeigen uses the eye icon for visitors and a star for favourites.

This is kinda irritating, because as a frequent user of Kleinanzeigen I'm used to their UI. Therefore AnzeigenChef should use the same icons for displaying the number of visitors and favourites.

**Comment by gastonx** [comment]
Thank you, is fixed.
