### ISSUE TITLE
Missing "Send now" Dialog

### ISSUE THREAD

**Issue by schwedenmut** [gastonx/AnzeigenChef-Mac#6]
Betrifft Version 2.0 (1)
Sobald man Anzeigen hochlädt, bekommt man leider den Spinning Ball of Death angezeigt. Wäre es nicht besser, wenn man einen Dialog angezeigt bekommt und auch weiter in der Applikation arbeiten könnte?

Darüber hinaus, sobald man viele Anzeigen hochladen möchte, bekommt man die "Fehlermeldung", dass man bitte die Zeichen (CAPTCHA) eingeben solle, was durch die Applikation nicht möglich ist. Leider wird danach dennoch die Liste der Anzeigen abgearbeitet - auch wenn diese von Kleinanzeigen nicht mehr angenommen werden.
(ansonsten super Applikation)

**Comment by gastonx** [comment]
Vielen Dank für Deinen Beitrag. Dieser Ladeprozess entsteht leider durch die Bilder, ich werde aber den Gesamtprozess wie auch von Dir vorgeschlagen in den Hintergrund (Thread) befördern und einen entsprechenden Fortschrittsdialog anzeigen.

Das Captcha kommt, soweit ich bisher rausgefunden habe, wenn mehrere Anzeigen in zu kurzem Abstand hochgeladen werden. Ich prüfe noch, wie lang die Pause sein muss, Anzeigen werden dann im Dialog mit einer entsprechenden Pause versehen. Damit sollte das nicht mehr passieren.

Ich halte Dich hier auf dem laufenden.

**Comment by gastonx** [comment]
Die Funktion wurde implementiert.
