### ISSUE TITLE
Sortierart wird nicht angepasst in der Anzeige

### ISSUE THREAD

**Issue by schwedenmut** [gastonx/AnzeigenChef-Mac#9]
Ich bins nochmal - wenn man die Sortierung ändert, wird das nicht in der Anzeige abgeändert - ist das gewollt?
![bildschirmfoto 2015-07-22 um 12 08 35](https://cloud.githubusercontent.com/assets/9077622/8823081/71fb2d84-306a-11e5-8ca3-09016236092b.png)

**Comment by gastonx** [comment]
Danke, im eingebaut.
